/* global Sabre */
Sabre.pack('Sabre.lg', function(S) {
    'use strict'
    this.CT_QC_PATTERN = [
        { Description: "Good", BitPattern: "/d773vvuAAC+/r7+f34AAPfu7/bv9gAA", Height: 12, Width: 15, ForegroundColor: "rgb(00,ff,00)", BackgroundColor: "rgb(00,ff,00)" },
        { Description: "Warning", BitPattern: "/d773vvuAAC+/r7+f34AAPfu7/bv9gAA", Height: 12, Width: 15, ForegroundColor: "rgb(ff,ff,00)", BackgroundColor: "rgb(ff,ff,00)" },
        { Description: "Bad", BitPattern: "/d773vvuAAC+/r7+f34AAPfu7/bv9gAA", Height: 12, Width: 15, ForegroundColor: "rgb(ff,00,00)", BackgroundColor: "rgb(ff,00,00)" }
    ];

    this.CT_STD_PATTERN = [
        { Description: "Water", BitPattern: "/////w==", Height: 1, Width: 32 },
        { Description: "Coal", BitPattern: "AAAAAA==", Height: 1, Width: 32 },
        { Description: "Moil", BitPattern: "/////93d3d3/////d3d3dw==", Height: 4, Width: 32 },
        { Description: "Lime", BitPattern: "AAAAAP9/////f////3////9/////f////3////9///8AAAAA////f////3////9/////f////3////9/////fw==", Height: 16, Width: 32 },
        { Description: "Dolo", BitPattern: "//3///8A//v///8A//f///8A/+////8A/9////8A/7////8A/3////8AAAAAAAAA/////f8A////+/8A////9/8A////7/8A////3/8A////v/8A////f/8AAAAAAAAA", Height: 16, Width: 40 },
        { Description: "Anhydrate1", BitPattern: "/v7+/v7+/f39/f39+/v7+/v79/f39/f37+/v7+/v39/f39/fv7+/v7+/f39/f39//v7+/v7+/f39/f39+/v7+/v79/f39/f37+/v7+/v39/f39/fv7+/v7+/f39/f39/", Height: 16, Width: 48 },
        { Description: "Igne", BitPattern: "////////4AD////////gAN//3//f/+AA3//f/9//4ADf/9//3//gAN//3//f/+AA3//f/9//4ADf/9//3//gAN//3//f/+AAwD/AP8A/4AD////////gAP///////+AA////////4AD////////gAP///////+AA/+//7//v4AD/7//v/+/gAP/v/+//7+AA/+//7//v4AD/7//v/+/gAP/v/+//7+AA/+//7//v4AD/4B/gH+AAAP///////+AA", Height: 24, Width: 51 },
        { Description: "Shale1", BitPattern: "/////////////////////////////////////wAAAP//////////////////////////////////////AP8AAA==", Height: 16, Width: 32 },
        { Description: "Shale2", BitPattern: "/////////////////////////////////////wAA//////////////////////////////////////////8AAA==", Height: 16, Width: 32 },
        { Description: "Gas", BitPattern: "////////////////////////z8/Pz8/P/////////////////////////Pz8/Pz8////////////////////////z8/Pz8/P/////////////////////////Pz8/Pz8", Height: 16, Width: 48 },
        { Description: "Sand", BitPattern: "////////////////Pz8/Pz8/Pz/////////////////////////////////n5+fn5+fn5////////////////w==", Height: 16, Width: 32 },
        { Description: "Anhydrate2", BitPattern: "///////g///////g7777///g9113///g+uuv///g/fff///g+uuv///g9113///g7777///g///////g///////g333////g///////g///9999g///+667g////XXXg////vvvg////XXXg///+667g///9999g///////g///////g", Height: 22, Width: 43 },
        { Description: "Glauconite", BitPattern: "/////8AA/////8AA/////8AA/////8AA/////8AA/vv//8AA/3f//8AA/6///8AA/9///8AA/6///8AA/3f//8AA/vv//8AA/////8AA/////8AA/////8AA/////8AA/////8AA/////8AA////fcAA////u8AA////18AA////78AA////18AA////u8AA////fcAA/////8AA/////8AA/////8AA", Height: 28, Width: 34 },
        { Description: "Bituminous", BitPattern: "//////////////////////D//x/w//8f8P//H/D//x/w//8f8P//H/D//x//////////////////////////////////////////////////H/D//x/w//8f8P//H/D//x/w//8f8P//H/D///////////////////////////8=", Height: 32, Width: 32 },
        { Description: "Pebble", BitPattern: "///////w///////w+D/////w99/////w76/////w72/////w7u/////w7e/////w6+/////w99/////w+D/////w///////w///////w///////w////g//w////ff/w///+/v/w///+/v/w///+/v/w///+/v/w///+/v/w////ff/w////g//w///////w///////w", Height: 25, Width: 44 },
        { Description: "Shell", BitPattern: "////////gAD//B////+AAP/j4////4AA/5/8////gAD/f/9///+AAP7//7///4AAvv/vv///gAC//+////+AAN///////4AA5/8/////gAD4+P////+AAP8H/////4AA//////B/gAD/////j4+AAP////5/84AA/////f/9gAD////7//6AAP///vv/voAA///+//+/gAD///9//3+AAP///5/8/4AA////4+P/gAD////8H/+AAP///////4AA", Height: 24, Width: 49 },
        { Description: "Shaley", BitPattern: "/////////////////////////////////////wD//wH/////////////////////////////////////////////////////////////////////////////////AQD///////////////////////////////////////////8=", Height: 32, Width: 32 },
        { Description: "Sandy", BitPattern: "//////////////////////////////////////P8P8/z/D/P//////////////////////////////////////////////////////////////////////////8/z/P8P8/z/P////////////////////////////////////8=", Height: 32, Width: 32 },
        { Description: "Shale3", BitPattern: "AADwD/////////////////////////////////////////////////////////////////////////////////APAAD///////////////////////////////////////////////////////////////////////////////8=", Height: 32, Width: 32 },
        { Description: "Finesand", BitPattern: "/////7+/v7/////////////////7+/v7//////////8=", Height: 8, Width: 32 },
        { Description: "Coarsesand", BitPattern: "7//v/8f/x//v/+/////////v/+//x//H/+//7/////8=", Height: 8, Width: 32 },
        { Description: "Lime2", BitPattern: "///+/////v////7////+/////v////7////+/////v////7////+/////v////7////+/////v////7/AAAAAP7////+/////v////7////+/////v////7////+/////v////7////+/////v////7////+/////v///wAAAAA=", Height: 32, Width: 32 },
        { Description: "Dolo2", BitPattern: "AAAAAP/9/////f////v////7////9/////f////v////3////9////+/////v////3////9////+////AAAAAP////7////9/////f////v////7////9/////f////v////3////9////+/////v////3////9////+/w==", Height: 31, Width: 32 },
        { Description: "CalDol", BitPattern: "fv/+AH3//gB7//4Ad//+AG///gBf//4AP//+AH///gB///4Af//+AH///gB///4Af//+AH///gB///4AAAAAAA==", Height: 16, Width: 23 },
        { Description: "LimeSub", BitPattern: "/v/+//7//v/+//7//v/+//7//v/+//7//v/+/wAAAAD//v/+//7//v/+//7//v/+//7//v/+//7//v/+AAAAAA==", Height: 16, Width: 32 },
        { Description: "ComShale", BitPattern: "////////////////AAAAAP////////////////////8=", Height: 8, Width: 32 },
        { Description: "Anhydrite", BitPattern: "fX19fbu7u7vX19fX7+/v79fX19e7u7u7fX19ff7+/v4=", Height: 8, Width: 32 },
        { Description: "Silex", BitPattern: "/v7+/v7+/f39/f39+/v7+/v79/f39/f37+/v7+/v39/f39/fv7+/v7+/f39/f39//v7+/v7+/f39/f39+/v7+/v79/f39/f37+/v7+/v39/f39/fv7+/v7+/f39/f39/", Height: 16, Width: 48 },
        { Description: "Salt", BitPattern: "////////////////////////////////9//3//f/9//3//f/9//3//f/9//3//f/9//3//f/9//3//f/9//3//f/8B/wH/Af////////////////////////////////", Height: 16, Width: 48 },
        { Description: "Sylvite", BitPattern: "/////////////////////zfwN/D39/f39/f39/f39/f39/f39/f39/f39/cH9gf2/////////////////////w==", Height: 16, Width: 32 },
        { Description: "Gypsum", BitPattern: "//////////////////////////9//3//v/6//t/93/3v++/79/f39/vv++///////////////////////////////////////////////////////3//f/6//r/93/3f++/77/f39/fv++/7//////////////////////////8=", Height: 32, Width: 32 },
        { Description: "Quartz", BitPattern: "3/v//9/7//9ZmpmZWZqZmd/7///f+///3/v//wAAAADf+9/73/vf+1maWZpZmlma3/vf+9/73/vf+9/7AAAAAP//3/v//9/7mZlZmpmZWZr//9/7///f+///3/sAAAAA//////////+ZmZmZmZmZmf///////////////wAAAAA=", Height: 32, Width: 32 },
        { Description: "Ingeous2", BitPattern: "///AAP//wAD//sAA//3AAP/7wAD/98AA/+/AAP/fwAD/v8AA/3/AAP7/wAD9/8AA+//AAP//wAD//8AA///AAP//wAD//8AA/9/AAP/fwAD/38AA/9/AAP/fwAD4AMAA/9/AAP/fwAD/38AA/9/AAP/fwAD//8AA///AAP//wAA=", Height: 32, Width: 18 },
        { Description: "Discontinuity", BitPattern: "//////////////////////////////////////////////////////////////////////////8AAAAAtm22bdmW2ZZH40fjP/w//P////////////////////////////////////////////////////////////////////8=", Height: 32, Width: 32 },
        { Description: "Gray0", BitPattern: "//////////////////////////////////////////8=", Height: 8, Width: 32 },
        { Description: "Gray1", BitPattern: "7+/v7/////////////////7+/v7///////////////8=", Height: 8, Width: 32 },
        { Description: "Gray2", BitPattern: "z8/Pz/////////////////z8/Pz///////////////8=", Height: 8, Width: 32 },
        { Description: "Gray3", BitPattern: "8/Pz8/Pz+/v7+/v7////////////////Pz8/Pz8/v7+/v7+/////////////////8/Pz8/Pz+/v7+/v7////////////////Pz8/Pz8/v7+/v7+/////////////////", Height: 16, Width: 48 },
        { Description: "Gray4", BitPattern: "/4CfgJ+A/4D/gPmA+YD/gP+A", Height: 9, Width: 9 },
        { Description: "Gray5", BitPattern: "/4CPgJ+A/4D/gPiA+YD/gP+A", Height: 9, Width: 9 },
        { Description: "Gray6", BitPattern: "HwAfAP8A/wDxAPEA/wD/AA==", Height: 8, Width: 8 },
        { Description: "Gray7", BitPattern: "HwAfAL8A/wDxAPEA+wD/AA==", Height: 8, Width: 8 },
        { Description: "Gray8", BitPattern: "HwAfAD8A/wDxAPEA8wD/AA==", Height: 8, Width: 8 },
        { Description: "Gray9", BitPattern: "j4+Pj4+Pj4+Pj4+P//////j4+Pj4+Pj4+Pj4+P////8=", Height: 8, Width: 32 },
        { Description: "Gray10", BitPattern: "HwAPAB8A/wDxAPAA8QD/AA==", Height: 8, Width: 8 },
        { Description: "Gray11", BitPattern: "HwAPAA8A/wDxAPAA8AD/AA==", Height: 8, Width: 8 },
        { Description: "Gray12", BitPattern: "Dw8PDw8PDw8PDw8P//////Dw8PDw8PDw8PDw8P////8=", Height: 8, Width: 32 },
        { Description: "Gray13", BitPattern: "DwAPAA8A3wDwAPAA8AD9AA==", Height: 8, Width: 8 },
        { Description: "Gray14", BitPattern: "Dw8PDw8PDw8PDw8Pn5+fn/Dw8PDw8PDw8PDw8Pn5+fk=", Height: 8, Width: 32 },
        { Description: "Gray15", BitPattern: "DwAPAA8AHwDwAPAA8ADxAA==", Height: 8, Width: 8 },
        { Description: "Gray16", BitPattern: "Dw8PDw8PDw8PDw8PDw8PD/Dw8PDw8PDw8PDw8PDw8PA=", Height: 8, Width: 32 },
        { Description: "Gray17", BitPattern: "cAAPAA8ADwAHAPAA8ADwAHAA", Height: 8, Width: 9 },
        { Description: "Gray18", BitPattern: "cADwAPAAcAAHAA8ADwAHAA==", Height: 8, Width: 8 },
        { Description: "Gray19", BitPattern: "YADwAPAAcAAGAA8ADwAHAA==", Height: 8, Width: 8 },
        { Description: "Gray20", BitPattern: "BgYGBg8PDw8PDw8PBgYGBmBgYGDw8PDw8PDw8GBgYGA=", Height: 8, Width: 32 },
        { Description: "Gray21", BitPattern: "YADwAPAAQAAGAA8ADwAEAA==", Height: 8, Width: 8 },
        { Description: "Gray22", BitPattern: "BgYGBg8PDw8PDw8PAAAAAGBgYGDw8PDw8PDw8AAAAAA=", Height: 8, Width: 32 },
        { Description: "Gray23", BitPattern: "YADgAPAAAAAGAA4ADwAAAA==", Height: 8, Width: 8 },
        { Description: "Gray24", BitPattern: "YADgAOAAAAAGAA4ADgAAAA==", Height: 8, Width: 8 },
        { Description: "Gray25", BitPattern: "AgICAgcHBwcHBwcHAAAAACAgICBwcHBwcHBwcAAAAAA=", Height: 8, Width: 32 },
        { Description: "Gray26", BitPattern: "AAAAAAcHBwcHBwcHAAAAAAAAAABwcHBwcHBwcAAAAAA=", Height: 8, Width: 32 },
        { Description: "Gray27", BitPattern: "YADgAAAAAAAGAA4AAAAAAA==", Height: 8, Width: 8 },
        { Description: "Gray28", BitPattern: "AAAAAAYGBgYGBgYGAAAAAAAAAABgYGBgYGBgYAAAAAA=", Height: 8, Width: 32 },
        { Description: "Gray29", BitPattern: "wABAAAAAAAAMAAQAAAAAAA==", Height: 8, Width: 8 },
        { Description: "Gray30", BitPattern: "AAAAAAYGBgYAAAAAAAAAAAAAAABgYGBgAAAAAAAAAAA=", Height: 8, Width: 32 },
        { Description: "Gray31", BitPattern: "AAAAAAICAgIAAAAAAAAAAAAAAAAgICAgAAAAAAAAAAA=", Height: 8, Width: 32 },
        { Description: "Gray32", BitPattern: "AAAAAA==", Height: 1, Width: 32 },
        { Description: "Limestone1", BitPattern: "AAAAAP7//v/+//7//v/+//7//v/+//7//v/+//7//v8AAAAA//7//v/+//7//v/+//7//v/+//7//v/+//7//g==", Height: 16, Width: 32 },
        { Description: "Limestone2", BitPattern: "AAAAAP9/////f////3////9/////f////3////9///8AAAAA////f////3////9/////f////3////9/////fw==", Height: 16, Width: 32 },
        { Description: "Limestone3", BitPattern: "AAAAAP/+/////v////7////+/////v////7////+/////v////7////+/////v////7////+/////v////7//wAAAAD////+/////v////7////+/////v////7////+/////v////7////+/////v////7////+/////v////4=", Height: 32, Width: 32 },
        { Description: "Dolomitic Limestone", BitPattern: "AAAAAAAA/////oAA/////YAA////+4AA////94AA////74AA////34AA////v4AA/////4AA//7//4AA//3//4AA//v//4AA//f//4AA/+///4AA/9///4AA/7///4AA", Height: 16, Width: 33 },
        { Description: "Chalk", BitPattern: "AAAAAP/+/////v////7////+/////v////7////+/////v////7////+/////v////7////+/////v////7//wfAB8D////+/////v////7////+/////v////7////+/////v////7////+/////v////7////+/////v////4=", Height: 32, Width: 32 },
        { Description: "Oolitic Limestone", BitPattern: "4P/7/99/+/+/v/v/f9/7/3vf+/9x3/v/e9/7/3/f+/+/v/v/33/7/+D/+/////v////7/wAAAAD7////+/////v/4P/7/99/+/+/v/v/f9/7/3vf+/9x3/v/e9/7/3/f+/+/v/v/33/7/+D/+/////v///8=", Height: 32, Width: 29 },
        { Description: "Nodular Limestone", BitPattern: "AAAAAAAAAAAAAH////+/////AAB/////v////wAAf/gP/7/8B/8AAH/n8/+/8/n/AAB/3/3/v+/+/wAAf7/+/7/f/38AAH9//3+/v/+/AAB/f/9/v7//vwAAf3//f7+//78AAH+//v+/3/9/AAB/3/3/v+/+/wAAf+fz/7/z+f8AAH/4D/+//Af/AAB/////v////wAAf////7////8AAAAAAAAAAAAAAAD//3////+//4AA//9/////v/+AAA//f/wH/7/8AADz/3/z+f+/84AA/f9/7/7/v++AAP7/f9//f7/fgAD/f3+//7+/v4AA/39/v/+/v7+AAP9/f7//v7+/gAD+/3/f/3+/34AA/f9/7/7/v++AAPP/f/P5/7/zgAAP/3/8B/+//AAA//9/////v/+AAP//f////7//gAA=", Height: 32, Width: 65 },
        { Description: "Phosphatic Limestone", BitPattern: "AAAAAAAAAAAAAH////+/////AAB/////v////wAAf/gP/7/8B/8AAH/gA/+/8AH/AAB/wAH/v+AA/wAAf4AA/7/AAH8AAH8AAH+/gAA/AAB/AAB/v4AAPwAAfwAAf7+AAD8AAH+AAP+/wAB/AAB/wAH/v+AA/wAAf+AD/7/wAf8AAH/4D/+//Af/AAB/////v////wAAf////7////8AAAAAAAAAAAAAAAD//3////+//4AA//9/////v/+AAA//f/wH/7/8AAAD/3/wAf+/8AAAAf9/4AD/v+AAAAD/f8AAf7/AAAAAf3+AAD+/gAAAAH9/gAA/v4AAAAB/f4AAP7+AAAAA/3/AAH+/wAAAAf9/4AD/v+AAAAP/f/AB/7/wAAAP/3/8B/+//AAA//9/////v/+AAP//f////7//gAA=", Height: 32, Width: 65 },
        { Description: "Sandy Limestone", BitPattern: "AAAAAAAAAAAAAP////9/////AAD/////f////wAA/////3////8AAP////9/////AAD/////f////wAA//7//3//f/8AAP/8f/9//j//AAD/+D//f/wf/wAA//x//3/+P/8AAP/+//9//3//AAD/////f////wAA/////3////8AAP////9/////AAD/////f////wAA/////3////8AAAAAAAAAAAAAAAD//v////9//4AA//7/////f/+AAP/+/////3//gAD//v////9//4AA//7/////f/+AAP/+//7//3//AAB//v/8f/9//gAAP/7/+D//f/wAAH/+//x//3/+AAD//v/+//9//wAA//7/////f/+AAP/+/////3//gAD//v////9//4AA//7/////f/+AAP/+/////3//gAA=", Height: 32, Width: 65 },
        { Description: "Shaley Limestone", BitPattern: "//3////9//7//f////3//v/9/////f/+//3////9//7//f////3//v/9/////f/+AP3wAAB98AD//f////3//v/9/////f/+//3////9//7//f////3//v/9/////f/+//3////9//7//f////3//gAAAAAAAAAA/////f////z////9/////P////3////8/////f////z////9/////P////3////8/////f////zwAAB98AAAPP////3////8/////f////z////9/////P////3////8/////f////z////9/////P////3////8AAAAAAAAAAA=", Height: 31, Width: 63 },
        { Description: "Fossiliferous Limestone", BitPattern: "AAAAAAAAAAB/////f////3//A/9//wP/f/78/3/+/P9//f9/f/3/f3/9/39//f9/f/v/v3/7/79/+/+/f/v/v377779++++/fv/v/37/7/9+/+//fv/v/39/3/9/f9//f3/f/39/3/9/nz//f58//3/g//9/4P//f////3////8AAAAAAAAAAP//f////3//A/9//wP/f//8/3/+/P9//v9/f/3/f3/9/39//f9/f/3/v3/7/79/+/+/f/v/v3/7779++++/fvvv/37/7/9+/+//fv/v/37/3/9/f9//f3/f/39/3/9/fz//f58//3+f//9/4P//f+D//3////9//w==", Height: 32, Width: 64 },
        { Description: "Bituminous Limestone", BitPattern: "AAAAAAAAAAAAAH////+/////gAB/////v////4AAf/4P/7/+D/+AAH/8B/+//Af/gAB/+AP/v/gD/4AAf/AB/7/wAf+AAH4AAA++AAAPgAB+AAAPvgAAD4AAfgAAD74AAA+AAH/wAf+/8AH/gAB/+AP/v/gD/4AAf/wH/7/8B/+AAH/+D/+//g//gAB/////v////4AAf////7////+AAAAAAAAAAAAAAAD//3////+//8AA//9/////v//AAB//f/4P/7/+AAAP/3/8B/+//AAAB/9/+AP/v/gAAAP/f/AB/7/wAAAAH34AAA++AAAAAB9+AAAPvgAAAAAffgAAD74AAAAD/3/wAf+/8AAAB/9/+AP/v/gAAA//f/wH/7/8AAAf/3/+D/+//gAA//9/////v//AAP//f////7//wAA=", Height: 32, Width: 66 },
        { Description: "Dolomite1", BitPattern: "AAAAAH////9/////f////3////9/////f////3////97////e////3f///93////b////2////9f////P////wAAAAD//3////9/////f////3////9/////f////3////97////e////3f///93////b////2////9f////P/8=", Height: 32, Width: 32 },
        { Description: "Dolomite2", BitPattern: "AAAAAP/9/////f////v////7////9/////f////v////3////9////+/////v////3////9////+////AAAAAP////7////9/////f////v////7////9/////f////v////3////9////+/////v////3////9////+/w==", Height: 31, Width: 32 },
        { Description: "Calcareous Dolomite", BitPattern: "AAAAAAAA/////vwA/////fwA/////fwA////+/wA////+/wA////9/wA////9/wA///97/wA///93/wA///93/wA///9v/wA///9v/wA///9f/wA///9f/wA///8//wAAAAAAAAA//7///wA//3///wA//3///wA//v///wA//v///wA//f///wA//f///wA/e////wA/d////wA/d////wA/b////wA/b////wA/X////wA/X////wA/P////wA", Height: 32, Width: 38 },
        { Description: "Sandy Dolomite", BitPattern: "AAAAAP////3////9////+/////v/7//3/8f/9/+D/+//x//f/+//3////7////+/////f////3////7/AAAAAP/+/////f////3////7////+/////f/7//3/8f/7/+D/9//x//f/+//v////7////9/////f////v///w==", Height: 31, Width: 32 },
        { Description: "Shaley Dolomite", BitPattern: "f////wAA/////oAA/////oAA/////YAA/////YAA////+4AA////+4AA4AAD94AA////74AA////74AA////34AA////34AA////v4AA////v4AA////f4AAAAAAAAAA//9//4AA//7//4AA//7//4AA//3//4AA//3//4AA//v//4AA//v//4AAA/fgAAAA/+///4AA/+///4AA/9///4AA/9///4AA/7///4AA/7///4AA/3///4AAAAAAAAAA", Height: 32, Width: 33 },
        { Description: "Evaporite", BitPattern: "AAAAAH9/f39/f39/f39/f39/f39/f39/f39/f39/f38AAAAAf39/f39/f39/f39/f39/f39/f39/f39/f39/fw==", Height: 16, Width: 32 },
        { Description: "Anhydrite", BitPattern: "/v7+/n19fX27u7u719fX1+/v7+/X19fXu7u7u319fX0=", Height: 8, Width: 32 },
        { Description: "Gypsum", BitPattern: "//////////////////7//n/9f/1//X/9v/u/+7/7v/vf99/33/ff9+/v7+/v7+/v//////////////////////////////////////7//v/9f/1//X/9f/u/+7/7v/u/99/33/ff99/v7+/v7+/v7/////////////////////8=", Height: 32, Width: 32 },
        { Description: "Halite", BitPattern: "f/9//3//f/9//3//f/8A//////////////////////8=", Height: 16, Width: 16 },
        { Description: "K Mg Salts", BitPattern: "//////////////////////AP8A/37/fv9+/37/fv9+/37/fv9+/37/fv9+/wD/AP/////////////////////w==", Height: 16, Width: 32 },
        { Description: "Sandstone Coarse", BitPattern: "/////+//7//H/8f/7//v////////7//v/8f/x//v/+8=", Height: 8, Width: 32 },
        { Description: "Sandstone Fine", BitPattern: "///////////7+/v7////////////////v7+/v/////8=", Height: 8, Width: 32 },
        { Description: "Shaley Sandstone", BitPattern: "4DwPAP////7////+/////v7+/v7////+/////v////6A8DwG/////v////7////+7+/v7v////7////+/////g==", Height: 16, Width: 31 },
        { Description: "Siltstone", BitPattern: "///////////g7uDu////////////////7uDu4P///////////////+Du4O7////////////////u4O7g/////w==", Height: 16, Width: 32 },
        { Description: "Shale1", BitPattern: "/////////////////////wAAAAD///////////////8=", Height: 8, Width: 32 },
        { Description: "Shale2", BitPattern: "/////////////////////////////////////wAA/wD//////////////////////////////////////wAAAA==", Height: 16, Width: 32 },
        { Description: "Calcareous Shale", BitPattern: "//////////////////////f////3////9////wAAfwD////////////////////////3////9/////f/fwAAAA==", Height: 16, Width: 32 },
        { Description: "Dolomite Shale", BitPattern: "////7/wA////3/wA////v/wA////f/wA///+//wA///9//wA///7//wA///3//wA///v//wA///f//wA//+///wA//9///wA//7///wA//3///wA//v///wAAAAAAAAA", Height: 16, Width: 38 },
        { Description: "Conglomerate", BitPattern: "8H///+A////AH///gA///wAH//8AB///AAf//4AP///AH///4D////B/////////////////////////////////4D///4AP//8AB//+AAP//AAB//wAAf/8AAH//gAD//8AB///gA///+A///////////////////////////8=", Height: 32, Width: 32 },
        { Description: "Breccia", BitPattern: "//////////////////7//n/8f/x//H/8P/g/+D/4P/gf8B/wH/Af8A/gD+AP4A/g//////////////////////////////////////7//v/8f/x//H/8f/g/+D/4P/g/8B/wH/Af8B/gD+AP4A/gD/////////////////////8=", Height: 32, Width: 32 },
        { Description: "Quartzite", BitPattern: "AAAAAP///////////////5mZmZmZmZmZ//////////8AAAAA///73///+9////vfmZmaWZmZmln///vf///73wAAAAD73/vf+9/73/vf+9+aWZpZmlmaWfvf+9/73/vfAAAAAPvf///73///+9///5pZmZmaWZmZ+9////vf//8=", Height: 32, Width: 32 },
        { Description: "Chert", BitPattern: "/v7+/v7+/f39/f39+/v7+/v79/f39/f37+/v7+/v39/f39/fv7+/v7+/f39/f39//v7+/v7+/f39/f39+/v7+/v79/f39/f37+/v7+/v39/f39/fv7+/v7+/f39/f39/", Height: 16, Width: 48 },
        { Description: "Igneous1", BitPattern: "f///4H///+B////gf///4H///+B////gf///4IB//+D////g////4P///+D////g////4P///+D////g/7//4P+//+D/v//g/7//4P+//+D/v//g/7//4P/AP+D////g////4P///+D////g////4P///+D////g////4A==", Height: 31, Width: 27 },
        { Description: "Igneous2", BitPattern: "++//77/w++//77/w++//77/w++//77/w++//77/wAAD/77/w++//77/w++//77/w++//77/w++//77/w++//77/w///////w///////w///////w///////w///////w///////w///////w///////w/v//+//w/ff/99/w++//77/w99//33/w77//vv/w33//ff/wvv/++//wff/99//w+///7//w///////w///////w///////w///////w", Height: 32, Width: 44 },
        { Description: "No Formation", BitPattern: "", Height: 0, Width: 0 },
        { Description: "Fracture Height", BitPattern: "Pj4+Pl5eXl5ubm5udnZ2dnp6enp8fHx8fn5+fn5+fn4=", Height: 8, Width: 32, ForegroundColor: "#004040", BackgroundColor: "#0f0" },
        { Description: "Open Hole Section", BitPattern: "5+fn59vb29u9vb29fn5+fg==", Height: 4, Width: 32 },
        { Description: "Perforation", BitPattern: "5+fn55mZmZm9vb29fn5+fn5+fn69vb29mZmZmefn5+c=", Height: 8, Width: 32, ForegroundColor: "#f00" }
    ];

});